### ISSUE TITLE
Type checking for update values

### ISSUE THREAD

**Issue by stan-sack** [guregu/dynamo#138]
I've noticed that its possible to perform an update operation with an incorrect type:

```
type Car struct {
    ID          string
    Wheels int
    Color    string
}

err := db.Table("cars").Update("ID", "my-car").Set("Wheels", "red")
assert.Nil(err) // err will be nil and the model will update
```

For the above case, there wont be any errors until later when I try to fetch the model which will fail to parse the Dynamo data into the struct.

Is there an idiomatic way to check the type? I can potentially do it with reflection but I dont think its optimal

**Comment by guregu** [comment]
The Update operation, not being tied to structs, is intentionally flexible, because DynamoDB itself only type-checks your primary keys. As you've noticed, it will happily overwrite attributes with a different type.
I've considered adding an API for updating based on structs, but I'm not sure how exactly the semantics would work, given that Update can do a lot of fancy stuff, and if you have a full struct you can use Put instead.
Anyway, I agree that this would be useful, but I'm not sure how exactly it'd work or whether it's in the scope of the library. What we're looking at is something higher level and more ORM-like than what we currently have.

One thing that you can do is add a condition to your update, something like:
```go
db.Table("cars").Update("ID", "my-car").Set("Wheels", "red").If("attribute_type('Wheels', ?)", "S").Run()
```
(more info about `attribute_type()` [here](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html#Expressions.OperatorsAndFunctions.Functions))
This will fail if the attribute isn't a string (or if it doesn't exist). Maybe we could add a shorthand for this? Like `IfAttributeTypesMatch()` and try to figure it out automatically. It's probably possible.

BTW, I think using reflection for this is fine. This library already uses a ton of reflection, it's a necessity of automatically serializing objects. The time spent on reflection is infinitesimal compared to the network round trip a DynamoDB API call takes (we're talking nanoseconds vs milliseconds), so don't worry too much about it.

**Comment by stan-sack** [comment]
I wouldnt change the API. I think the fact that this issue exists is also enough documentation regarding the topic.

Thanks for the quick response and suggestions. I've just put together a hacky solution with reflection which serves my purpose pretty well:
```
type Car struct {
    ID          string
    Wheels int
    Color    string
}

func UpdateByID(ID string, fields map[string]interface{}) error {
	update := db.Table("cars").Update("ID", ID)
	for name, val := range fields {
		// check that the type is correct
		dummyVal := reflect.Zero(reflect.TypeOf(Car{})).FieldByName(name)
		if !dummyVal.IsValid() {
			return fmt.Errorf("Attribute: %s does not exist on model: Car", name)
		}
		valType := dummyVal.Type()
		if valType != reflect.TypeOf(val) {
			return fmt.Errorf("Incorrect type of %s for field %s. Expected %s", reflect.TypeOf(val), name, valType)
		}
		// add the value to the list of updates
		update = update.Set(name, val)
	}
	return update.Run()
}
```
