### ISSUE TITLE
LastEvaluatedKey may point unexpected position in case Limit is set to Query

### ISSUE THREAD

**Issue by kaneshu** [guregu/dynamo#186]
I'm getting paginated query result 10 items each by callilng Query.Limit(10) and pass LastEvaluatedKey returned to next query.
It seems to work correctly in usual cases, of course.
But in case DynamoDB divides result due to 1MB limitation, LastEvaluatedKey returned by dynamo points an item ahead of the last item of result.

To my understanding, in such a case dynamo iterates to query internally to fulfill the result with 10 items then return it to client.
But LastEvaluatedKey returned by DynamoDB in last query will not always match to the last item of returned to client.
It seems be because dynamo passes Limit = 10, which is the value I passed to dynamo, to DynamoDB in every iterating query and LastEvaluatedKey points the last item of list DynamoDB returned, but not the last item of list returned to client.

Is it an expected behavior?
Is there any way to get correct LastEvaluatedKey even in above case?

**Comment by guregu** [comment]
I agree it's not good behavior. LastEvaluatedKey was tacked on later and didn't really take this edge case into account.
This is something I want to fix in v2.

There's a couple ways you can deal with this:
- Use SearchLimit instead of Limit. This will disable the behavior that automatically iterates internally, and it'll be up to you to call it multiple times if you're using Filter, etc and you don't get enough results.
- This isn't documented anywhere, but there's nothing stopping you from just generating the LastEvaluatedKey based on the results you get. LastEvaluatedKey is just a `map[string]*dynamodb.AttributeValue` of the primary key. It will totally work if you just calculate this from the last item in the results. However, as far as I can see this isn't mentioned in the official documents. It seems to work though. We could fix this bug if we automatically did this, but I'm not sure if that's 100% correct 🤔 

I'll take another look at this soon and see if we can't handle this case automatically. Both of the strategies above should work, though.

**Comment by kaneshu** [comment]
I'm considering a workaround same as a second solution you presented.
I also think it will work. The only concern is that it's not documented officially.

Anyway, I will try it as short-term solution. 
I hope it will be solved in v2 or another future update.

Thank you.

**Comment by guregu** [comment]
I did some more research, and I think that it should be totally OK to use arbitrary results as the LastEvaluatedKey.
https://dev.classmethod.jp/articles/ddb-lastevaluatedkey/
It makes sense if you think about this use case where the LastEvaluatedKey's item is deleted before the scan starts.

Now the problem is: how do we automatically generate the LastEvaluatedKey?
We don't necessarily know the table's primary keys unless we call DescribeTable or examine a real LastEvaluatedKey.
90% of the time we should be able to figure out the primary keys by looking at the real LastEvaluatedKey's keys. Otherwise we'll have to call DescribeTable (and maybe cache the results...?).
There's also a corner case where Projection is used that excludes a hash or range key, in this case we wouldn't be able to calculate the LastEvaluatedKey at all.
Maybe this is harder than I thought.
Hmm... 🤔

**Comment by kaneshu** [comment]
Certainly that's a difficult problem...
I don't have a good idea about a way to calculate LastEvaluatedKey in any case.

How about a solution of reducing 'limit' parameter in query of 2nd or later iterating to match the number of remaining items to be acquired?

here is example flow:
- client calls Query.AllWithLastEvaluatedKeyContext() with Limit set to 10.
- dynamo requests query to DynamoDB with limit 10.
- DynamoDB returns only 7 items and LastEvaluatedKey due to 1MB limitation.
- dynamo requests query to DynamoDB with LastEvaluatedKey and limit 3.
- DynamoDB returns only 3 items and LastEvaluatedKey.
- dynamo returns the result and LastEvaluatedKey

in this case, LastEvaluatedKey always points the last item of the result, I think.

If we consider a case filter condition is specified, query of later iterating might be very inefficient.
But originally dynamo ignore Limit parameter and does not iterate query internally, so we don't have to consider filtering case.

It's just my idea and it have not been fully considered.

**Comment by guregu** [comment]
Should be fixed via #187.
The strategy I took is to examine the output LastEvaluatedKey, the input ExclusiveStartKey if that doesn't exist, and then DescribeTable as a last resort to grab the schema.
Because Limit and iterators were already "magic" provided by this library, I think it's an OK solution.
When it can't figure out how to generate a LastEvaluatedKey, it'll revert to the old behavior and log a warning, but this should never happen unless you're doing weird stuff with projections.

I'll release a new version soon.

**Comment by guregu** [comment]
Released in https://github.com/guregu/dynamo/releases/tag/v1.12.0 🚀

**Comment by kaneshu** [comment]
Great!
It seems to work fine with my test code also.

Thank you.
