### ISSUE TITLE
AWS errors

### ISSUE THREAD

**Issue by boyand** [guregu/dynamo#23]
First of all, thanks for putting this great library together - saves a lot of time! 

I have a question on the error handling. Most of the times the errors returned are the original AWS errors but this behaviour is inconsistent. For example for queries the errors are hidden behind custom ones: https://github.com/guregu/dynamo/blob/master/query.go#L42-L44.

Is there a reason for this? Would it make sense to always return the original AWS error messages so that the clients can decide how to deal with them and the error handling is consistent ?

**Comment by guregu** [comment]
Thanks!

Those errors don't replace AWS errors. For example: when you run a GetItem or Query request and don't get any results, AWS doesn't return an error but instead returns a null item or an empty list. Without returning ErrNotFound, it would be hard to tell whether you got any results at all. Since dynamo works based on unmarshaling into objects, you would have to inspect your object(s) to see if they are still uninitialized or something like that.

dynamo's Get function combines Query and GetItem, using the faster GetItem when possible (for single results) but will fall back to a slower Query if necessary. If you call Get().One() expecting one result but your query had more than one result, it will return ErrTooMany. This is to inform you of an error in your query design: something's wrong if you expect one result and get multiple. I've never seen this happen in practice.
