### ISSUE TITLE
Is there a no-internal-pagination mode for Scan/Query?

### ISSUE THREAD

**Issue by extemporalgenome** [guregu/dynamo#231]
Hi! I have workloads that are simpler to reason about and control if there were a way to run Scan/Query in this library such that:

1. Exactly one Scan/Query call in this library produces exactly one Scan/Query call in the underlying SDK. To scan subsequent pages, a new guregu Scan/Query invocation must be made.
2. I do not need to set a SearchLimit or Limit, and can rely on query results being bounded by DynamoDB's 1MB upper bound on single-response result set size.
3. All*, Next*, etc all work, except that they do not result in further implicit fetches. Instead, they'll stop, e.g. at that 1MB boundary if no other limit is reached first.
4. The LastEvaluatedKey is exactly the one that the SDK provides, and not one computed based on an intra-page result.

Rationale:
1. The code looks like an AllWithContext, passed a slice, will OOM unless a Limit is set: it looks like it'll keep fetching forever on a sufficiently large table.
2. Needing to set a SearchLimit to prevent buffering the whole table is awkward and less efficient, since we are removing the DynamoDB endpoint's ability to just maximize RCUs. i.e. 1MB of results will use no more than 125 RCU, but an arbitrary SearchLimit of 1000 may hypothetically do something like fetch a full 1MB page (very efficient) and then fetch 3 more results on the next page (very inefficient), and may continue that uneven walk over the whole table.
3. Fine-grained rate limiting of RCUs is far simpler with more explicit control over requests (i.e. ask for 125 rate limit tokens because I'm ensured I'll be fetching no more than 1MB over no more than 1 request).

Is there presently such a capability to do the above using this library?

If not, would you be open to it being added?
It seems like the simplest approach is some kind of `RequestLimit(1)` method call that can be used to achieve the above, potentially with a mechanism to reset it (`ResetRequestCounter()`) in order to reuse the constructed Scan/Query, while providing the application control over admitting requests.

**Comment by guregu** [comment]
Hello, thanks for the detailed issue.

It's a bit confusing, but if you set SearchLimit then it will always limit the amount of requests to 1. So you could set this to a high number and get the behavior you want. However, this becomes an issue when you're using filters: AWS will use the SearchLimit to do "server-side" pagination as it searches for filter matches and potentially use a lot of RCUs before it sends us the first page of results.

I can add a request limit parameter, but just keep in mind that in the case where you're using filters, you might get as few as zero results because it hasn't found any matches. Then you could use LastEvaluatedKey to continue the query later. Sound good?

BTW, LastEvaluatedKey will only be computed if you grab it in the middle of using an Iter that hasn't finished yet. AllWithLastEvaluatedKey etc. will always give you the "real" one. So a hypothetical `query.RequestLimit(1).AllWithContext(...)` will give you the behavior you're looking for.

**Comment by extemporalgenome** [comment]
> I can add a request limit parameter, but just keep in mind that in the case where you're using filters, you might get as few as zero results because it hasn't found any matches. Then you could use LastEvaluatedKey to continue the query later. Sound good?

Yep, that's exactly what I'm hoping for! This would clearly be used to obtain a bit of low level control for certain use-cases.

**Comment by guregu** [comment]
Cool, I'll add this real soon. I would appreciate it if you can test it before the official release, just to make sure it works with your use case. I'll comment with the commit hash when I get it in.

**Comment by guregu** [comment]
Alright, give this a shot:
```
go get github.com/guregu/dynamo@d5fb452
```

Adds `RequestLimit(int)` to Query and Scan.

**Comment by extemporalgenome** [comment]
Hi! I've tested this out with dynamodb-local on both scans and queries, and it normally behaves as I'd expect, however, when `Count()` is involved, it appears that `RequestLimit` is not respected.

Can `Count` also be updated to respect `RequestLimit` ?

Thanks!

**Comment by guregu** [comment]
RequestLimit is included in the latest release: [v1.23.0](https://github.com/guregu/dynamo/tree/v1.23.0)
Thanks for the help and let me know if you run into any issues

**Comment by extemporalgenome** [comment]
Thank you!
