### ISSUE TITLE
Expression attribute names in Projection

### ISSUE THREAD

**Issue by LibertyLocked** [guregu/dynamo#38]
If there's a reserved keyword in `Project` (e.g. "Name") the request would fail.

```go
// Project limits the result attributes to the given paths.
func (s *Scan) Project(paths ...string) *Scan {
	expr, err := s.subExpr(strings.Join(paths, ", "), nil)
	s.setError(err)
	s.projection = expr
	return s
}
```

Maybe it should use expression attribute names for the `paths`?

**Comment by guregu** [comment]
Hello, I think you can do `.Scan("'Name'")` and it will work, but there's no easy way to dynamically do it like `$` in filters.
I'm thinking instead of using `s.subExpr` we can run `s.escape` on each element of `paths` and it should automatically escape reserved words. I'll try it out.
Thanks for the issue!

**Comment by guregu** [comment]
With the new fixes `.Project("Name")` should work!
