### ISSUE TITLE
Library versioning

### ISSUE THREAD

**Issue by tetor** [guregu/dynamo#48]
Because aws/aws-sdk-go has breaking change about Configration, I often be encountered a conflict import lib error.

like this
```
script/try_dynamo.go:24: cannot use session.New() (type *session.Session) as type "github.com/guregu/dynamo/vendor/github.com/aws/aws-sdk-go/aws/client".ConfigProvider in argument to dynamo.New:
        *session.Session does not implement "github.com/guregu/dynamo/vendor/github.com/aws/aws-sdk-go/aws/client".ConfigProvider (wrong type for ClientConfig method)
                have ClientConfig(string, ...*"github.com/aws/aws-sdk-go/aws".Config) "github.com/aws/aws-sdk-go/aws/client".Config
                want ClientConfig(string, ...*"github.com/guregu/dynamo/vendor/github.com/aws/aws-sdk-go/aws".Config) "github.com/guregu/dynamo/vendor/github.com/aws/aws-sdk-go/aws/client".Config
```

Would you use a library versioning solution e.g. dep?

thank you;

**Comment by guregu** [comment]
Hello. I do want to start versioning the library soon (semver releases). I've been avoiding this because I sometimes broke the API, but it's been stable for at least a year now. 

This seems like an error caused by improper vendoring, not breaking changes. Instead of putting the AWS library inside of dynamo, try putting them both in the same vendor folder under your own project. Like this:
```
$GOPATH/src/github.com/me/myproject/
  main.go
  vendor/
    github.com/
      guregu/
        dynamo/
          ...
      aws/
        aws-sdk-go/
          ...
```
I can confirm that the above layout works well.
If you vendor AWS inside of dynamo, it will become incompatible because dynamo has its own separate copy, different from the rest of your program. Please let me know if I misunderstood something.

**Comment by flyinprogrammer** [comment]
What are people's thoughts on using [Go Modules](https://github.com/golang/go/wiki/Modules), and upgrading to [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) ?

**Comment by guregu** [comment]
@flyinprogrammer I've added support for Go modules. I'll think about migrating to the v2 SDK when it hits 1.0 and they start deprecating the current v1 SDK. It shouldn't be too hard to migrate to v2 when the time comes.
